akka {
  actor {
    provider = "cluster"
  }
  
  remote {
    artery {
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = ${?CLUSTER_PORT}
    }
  }
  
  cluster {
    # Single-node deployment: the node is its own seed. (Add more seed-nodes here
    # if you run a multi-node cluster.)
    seed-nodes = [
      "akka://ClusterSystem@127.0.0.1:2551"
    ]

    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
  }
  
  http {
    server {
      preview.enable-http2 = on
    }
  }
  
  loglevel = "INFO"
}

